# This source file was automatically generated by the awesome GitHub Copilot
# Tell me 3 funny jokes and put them to a list
jokes: list = [
    "Q: What do you call a fake noodle? A: An Impasta.",
    "Q: Why did the scarecrow win an award? A: Because his hedges didn't!",
    "Q: What do you call a cow with no legs? A: Ground beef."
]

print('\n'.join(jokes))

